name: pocket
favicon: null
layout_spectrum: 1
typography_spectrum: 0.4530922088306397
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#92449a'
    - '#ffffff'
    - '#29c6d2'
    - '#c2b4cb'
    - '#c2ef10'
  brandStrength: 1
  lightness: 0.75
  saturation: 0
  rhythmicContrast: 0.75
purpose: []
